name: bayesian  # for Bayesian analysis
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- missingno
- pymc3
- pygpu=0.6.9
- cython
- mkl-service
- scikit-learn
- autopep8
- matplotlib
- numpy
- pandas
- scipy
- seaborn
- jupyter
- jupyterlab
- ipykernel
- jupyterlab
- jupyter_contrib_nbextensions
- rise
- h5py
